### ISSUE TITLE
DBUS library failure

### ISSUE THREAD

**Issue by Ryccoo** [Devidian/docker-spaceengineers#3] opened 2020-11-29 23:55 UTC
Hi, I have tried running the example server, and it keeps failing after the IP Bind

````
Attaching to se-ds-docker-quickstart
se-ds-docker-quickstart | -------------------------------START------------------------------
se-ds-docker-quickstart | WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
se-ds-docker-quickstart | Redirecting stderr to '/root/Steam/logs/stderr.txt'
se-ds-docker-quickstart | [  0%] Checking for available updates...
se-ds-docker-quickstart | [----] Verifying installation...
se-ds-docker-quickstart | Steam Console Client (c) Valve Corporation
se-ds-docker-quickstart | -- type 'quit' to exit --
se-ds-docker-quickstart | Loading Steam API...OK.
se-ds-docker-quickstart |
se-ds-docker-quickstart | Connecting anonymously to Steam Public...Logged in OK
se-ds-docker-quickstart | Waiting for user info...OK
se-ds-docker-quickstart | "@sSteamCmdForcePlatformType" = "windows"
se-ds-docker-quickstart | Success! App '298740' already up to date.
se-ds-docker-quickstart | CWorkThreadPool::~CWorkThreadPool: work processing queue not empty: 1 items discarded.
se-ds-docker-quickstart | CWorkThreadPool::~CWorkThreadPool: work processing queue not empty: 3 items discarded.
se-ds-docker-quickstart | 2020-11-29 23:52:44.874: App Version: 01_197_065
se-ds-docker-quickstart | 2020-11-29 23:52:44.899: Is official: True [NO][NIS][NAMP]
se-ds-docker-quickstart | 2020-11-29 23:52:44.902: Environment.ProcessorCount: 1
se-ds-docker-quickstart | 2020-11-29 23:52:44.912: Environment.OSVersion: Microsoft Windows 7 Professional (Microsoft Windows NT 6.1.7601 Service Pack 1)
se-ds-docker-quickstart | 2020-11-29 23:52:44.912: Environment.CommandLine: "Z:\appdata\space-engineers\SpaceEngineersDedicated\DedicatedServer64\SpaceEngineersDedicated.exe" -noconsole -ignorelastsession -path Z:\appdata\space-engineers\instances\TestServerRich
se-ds-docker-quickstart | 2020-11-29 23:52:44.913: Environment.Is64BitProcess: True
se-ds-docker-quickstart | 2020-11-29 23:52:44.913: Environment.Is64BitOperatingSystem: True
se-ds-docker-quickstart | 2020-11-29 23:52:44.915: Environment.Version: .NET Framework 4.8.3761.0
se-ds-docker-quickstart | 2020-11-29 23:52:44.915: Environment.CurrentDirectory: Z:\appdata\space-engineers\SpaceEngineersDedicated\DedicatedServer64
se-ds-docker-quickstart | 2020-11-29 23:52:44.916: CPU Info: Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
se-ds-docker-quickstart | Computer does not meet minimum requirements, forcing Experimental mode
se-ds-docker-quickstart | 2020-11-29 23:52:53.259: Bind IP : 0.0.0.0:27016
se-ds-docker-quickstart | dbus[60]: arguments to dbus_connection_send_with_reply_and_block() were incorrect, assertion "connection != NULL" failed in file ../../../dbus/dbus-connection.c line 3544.
se-ds-docker-quickstart | This is normally a bug in some application using the D-Bus library.
se-ds-docker-quickstart |
se-ds-docker-quickstart |   D-Bus not built with -rdynamic so unable to print a backtrace
se-ds-docker-quickstart | wine: Assertion failed at address 00007F331D0737BB (thread 0078), starting debugger...
se-ds-docker-quickstart | 2020-11-29 23:53:13.202: Error: No IP assigned.
se-ds-docker-quickstart | --------------------------------END-------------------------------

````

**Comment by Devidian** [comment] 2020-11-30 06:55
Hey @Ryccoo the dbus is not the problem as i always get this message too. Your problem is that `No IP assigned` line. does your host have a internet connection? Is your host port 27016 free?

```log
se-ds-docker-quickstart | dbus[52]: arguments to dbus_connection_send_with_reply_and_block() were incorrect, assertion "connection != NULL" failed in file ../../../dbus/dbus-connection.c line 3544.
se-ds-docker-quickstart | This is normally a bug in some application using the D-Bus library.
se-ds-docker-quickstart | 
se-ds-docker-quickstart |   D-Bus not built with -rdynamic so unable to print a backtrace
se-ds-docker-quickstart | wine: Assertion failed at address 00007FF791EC47BB (thread 0064), starting debugger...
se-ds-docker-quickstart | 2020-11-30 06:50:53.088: Networking service: Steam
```

**Comment by Devidian** [comment] 2020-12-10 16:34
Is this issue still present?

**Comment by Devidian** [comment] 2020-12-17 10:15
Seems the problem is solved so i close this issue for now!

**Closed by Devidian** 2020-12-17 10:15 UTC

**Comment by Ryccoo** [comment] 2020-12-17 22:05
Sorry for the late reply,
I have set up a new environment on a new VM and the issue didn't reproduce, seems like it may have been VM related.
